### ISSUE TITLE
geoipupdate job fails if no changes present

### ISSUE THREAD

**Issue by rgraber** [openedx/ecommerce-scripts#204]
When there are no changes present, the geoipupdate job will error when it tries to commit. It should be updated to check that there are changes before trying to create a PR.

**Comment by rgraber** [comment]
This has so far only happened once in November 2023. May re-evaluate the priority if we either move this to Github actions or it happens again.

**Comment by jristau1984** [comment]
This has not come up again as a reported issue, so closing.
